/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficas_2D;

import javax.swing.JOptionPane;

/**
 *
 * @author Ing. Aristi!
 */
public class Acopladas extends javax.swing.JFrame {

    /**
     * Creates new form Acopladas
     */
    public Acopladas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        Circulos_arriba = new javax.swing.JButton();
        Circulos_abajo = new javax.swing.JButton();
        Circulos_centrados = new javax.swing.JButton();
        Imagen_acoplada = new javax.swing.JButton();
        Cuadro = new javax.swing.JButton();
        tablero = new javax.swing.JPanel();
        Borrar = new javax.swing.JButton();
        Salir1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Linea_1 = new javax.swing.JButton();
        Linea_2 = new javax.swing.JButton();
        Linea_3 = new javax.swing.JButton();

        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Circulos_arriba.setText("Circulos Arriba");
        Circulos_arriba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Circulos_arribaMouseClicked(evt);
            }
        });

        Circulos_abajo.setText("Circulo Centrado");
        Circulos_abajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Circulos_abajoMouseClicked(evt);
            }
        });
        Circulos_abajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Circulos_abajoActionPerformed(evt);
            }
        });

        Circulos_centrados.setText("Circulos Abajo");
        Circulos_centrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Circulos_centradosMouseClicked(evt);
            }
        });
        Circulos_centrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Circulos_centradosActionPerformed(evt);
            }
        });

        Imagen_acoplada.setText("Imagen Acoplada");
        Imagen_acoplada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagen_acopladaMouseClicked(evt);
            }
        });

        Cuadro.setText("Cuadro");
        Cuadro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CuadroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tableroLayout = new javax.swing.GroupLayout(tablero);
        tablero.setLayout(tableroLayout);
        tableroLayout.setHorizontalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tableroLayout.setVerticalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        Borrar.setText("Borrar");
        Borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BorrarMouseClicked(evt);
            }
        });

        Salir1.setText("Salir");
        Salir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir1MouseClicked(evt);
            }
        });

        jButton1.setText("A cerca de");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Linea_1.setText("Linea 1");
        Linea_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Linea_1MouseClicked(evt);
            }
        });

        Linea_2.setText("Linea 2");
        Linea_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Linea_2MouseClicked(evt);
            }
        });

        Linea_3.setText("Linea 3");
        Linea_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Linea_3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Linea_3)
                                .addGap(18, 18, 18)
                                .addComponent(Circulos_centrados, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Linea_1)
                                        .addGap(18, 18, 18)
                                        .addComponent(Circulos_arriba, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Linea_2)
                                        .addGap(18, 18, 18)
                                        .addComponent(Circulos_abajo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Imagen_acoplada)
                                    .addComponent(Cuadro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Circulos_arriba)
                            .addComponent(Cuadro)
                            .addComponent(Linea_1))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Circulos_abajo)
                            .addComponent(Imagen_acoplada)
                            .addComponent(Linea_2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Borrar)
                            .addComponent(Circulos_centrados)
                            .addComponent(Linea_3))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Salir1)
                        .addGap(33, 33, 33)))
                .addComponent(tablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Linea_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Linea_1MouseClicked
    Dibujar.HacerLinea(tablero.getGraphics(), 150, 50, 400, 200);
// TODO add your handling code here:
    }//GEN-LAST:event_Linea_1MouseClicked

    private void Linea_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Linea_2MouseClicked
    Dibujar.HacerLinea(tablero.getGraphics(), 400, 50, 150, 200);
// TODO add your handling code here:
    }//GEN-LAST:event_Linea_2MouseClicked

    private void Linea_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Linea_3MouseClicked
    Dibujar.HacerLinea(tablero.getGraphics(), 275, 50, 275, 200);
// TODO add your handling code here:
    }//GEN-LAST:event_Linea_3MouseClicked

    private void Circulos_arribaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Circulos_arribaMouseClicked
    Dibujar.HacerCirculo(tablero.getGraphics(), 150, 50, 50, 50);
    Dibujar.HacerCirculo(tablero.getGraphics(), 350, 50, 50, 50);
// TODO add your handling code here:
    }//GEN-LAST:event_Circulos_arribaMouseClicked

    private void Circulos_abajoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Circulos_abajoMouseClicked
    Dibujar.HacerCirculo(tablero.getGraphics(), 250, 100, 50, 50);
// TODO add your handling code here:
    }//GEN-LAST:event_Circulos_abajoMouseClicked

    private void Circulos_centradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Circulos_centradosMouseClicked
    Dibujar.HacerCirculo(tablero.getGraphics(), 150, 150, 50, 50);
    Dibujar.HacerCirculo(tablero.getGraphics(), 350, 150, 50, 50);
// TODO add your handling code here:
    }//GEN-LAST:event_Circulos_centradosMouseClicked

    private void CuadroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CuadroMouseClicked
    Dibujar.HacerCuadro(tablero.getGraphics(), 150, 50, 250, 150);
// TODO add your handling code here:
    }//GEN-LAST:event_CuadroMouseClicked

    private void Imagen_acopladaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagen_acopladaMouseClicked
    Dibujar.HacerLinea(tablero.getGraphics(), 150, 50, 400, 200);
    Dibujar.HacerLinea(tablero.getGraphics(), 400, 50, 150, 200);
    Dibujar.HacerLinea(tablero.getGraphics(), 275, 50, 275, 200);
    Dibujar.HacerCirculo(tablero.getGraphics(), 150, 50, 50, 50);
    Dibujar.HacerCirculo(tablero.getGraphics(), 350, 50, 50, 50);
    Dibujar.HacerCirculo(tablero.getGraphics(), 250, 100, 50, 50);
    Dibujar.HacerCirculo(tablero.getGraphics(), 150, 150, 50, 50);
    Dibujar.HacerCirculo(tablero.getGraphics(), 350, 150, 50, 50);
    Dibujar.HacerCuadro(tablero.getGraphics(), 150, 50, 250, 150);
// TODO add your handling code here:
    }//GEN-LAST:event_Imagen_acopladaMouseClicked

    private void BorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorrarMouseClicked
    tablero.repaint();
// TODO add your handling code here:
    }//GEN-LAST:event_BorrarMouseClicked

    private void Circulos_abajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Circulos_abajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Circulos_abajoActionPerformed

    private void Circulos_centradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Circulos_centradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Circulos_centradosActionPerformed

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirMouseClicked

    private void Salir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir1MouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_Salir1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(this, "Espero sea de tu agrado este ejercicio de gráficas, un abrazo!");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acopladas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acopladas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acopladas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acopladas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acopladas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Circulos_abajo;
    private javax.swing.JButton Circulos_arriba;
    private javax.swing.JButton Circulos_centrados;
    private javax.swing.JButton Cuadro;
    private javax.swing.JButton Imagen_acoplada;
    private javax.swing.JButton Linea_1;
    private javax.swing.JButton Linea_2;
    private javax.swing.JButton Linea_3;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Salir1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel tablero;
    // End of variables declaration//GEN-END:variables
}
